# w_p = c_p[1] * k + c_p[2] * k^2
C_LA: [9.01e+3, -2.0e-7] # [m/s, m^2/s]
C_TA: [5.23e+3, -2.26e-7]

LATTICE_DIST: 5.43e-10 # [m]

Ai: 1.498e-45 # s^3
BL: 1.18e-24 # K^{-3}
BT: 8.708e-13 # K^{-3}
BU: 2.890e-18 # s